### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by SamusAranX** [McKay42/mph-model-viewer#1]
![corrupted](https://user-images.githubusercontent.com/676069/41062535-63d268a0-69d6-11e8-9575-830493579cc3.PNG)

I was hoping to extract a few of my favorite levels for later use in Blender (favorite level not pictured here), but since all the textures in the final game are corrupted, no dice.

From one of the Youtube videos linked in the readme, I remember something about the palette being different. If you don't want to or can't fix this (due to time constraints or whatever, it's absolutely fine) and since attempting to decode unknown file formats is one of my favorite pastimes, I'd greatly appreciate it if you could add this program's source code to this repo, so I could try fixing this myself.

**Edit**: Alright, turns out that when devs say "do this, this tool won't work if you don't", they mean it. I forgot to copy the files to the models/ and textures/ folders.

My code request still stands, though. I'd really like to take a peek at how MPH's models are constructed.

**Comment by McKay42** [comment]
I never added the explanation to the readme here, but it's in the [release video](https://www.youtube.com/watch?v=BSn59ebjOnw).

The palette structure is not actually different. Some model files simply don't have the textures baked into the model file, but have a separate texture container file (e.g. for maps it would be in `/levels/textures/`).

Just extract all contents of `/levels/textures/` into `/<MPH Model Viewer>/mph/textures/`, do not rename any files (as the association between model and texture file is hardcoded `<modelname>_tex.bin`). This is why the textures folder exists.

The code is very messy, but if you really want to have it I can clean up a version without physics (so noclip movement only). (The engine source for physics/entities/player stuff is not yet ready to be public.)

**Comment by SamusAranX** [comment]
> Just extract all contents of /levels/textures/ into /<MPH Model Viewer>/mph/textures/, do not rename any files (as the association between model and texture file is hardcoded <modelname>_tex.bin). This is why the textures folder exists.

Yeah, I just noticed that. Silly me. 😄

> but if you really want to have it I can clean up a version without physics

That'd be super great. This game was a major part of my childhood. I can't wait to take it apart.

**Comment by McKay42** [comment]
If you compile your own executable, then some things will not work with the default engine configuration (texture exports, antialiasing). Also, everything will only work with the default OpenGL Legacy renderer.

To make texture exports work, comment the following line in `OpenGLImage.cpp`:
`m_rawImage = std::vector<unsigned char>();`

To enable antialiasing on Windows, uncomment the following block that starts with this in `main_Windows.cpp`:
```
/*
if (!g_bARBMultisampleSupported && true)
...
*/
```
